name: 自动打包Android Release APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 配置JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 赋予gradlew执行权限
        run: chmod +x gradlew

      - name: 打包Release APK
        run: ./gradlew assembleRelease

      - name: 上传APK供下载
        uses: actions/upload-artifact@v4
        with:
          name: my-release-apk
          path: app/build/outputs/apk/release/*.apk
